apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/naveenkumarhn/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - naveenkumar003/argo-combined-app:29b61cf6d711be151e0b96bb03a33f6a9fd6dd30
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
